# Generated by Django 3.2.4 on 2021-06-10 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Service_Company', to='trip.organization', verbose_name='fournisseur'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Insurance_Company', to='trip.organization', verbose_name='Assureur'),
        ),
        migrations.AddField(
            model_name='technicalcheckin',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.car', verbose_name='véhicule'),
        ),
        migrations.AddField(
            model_name='tax',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.car', verbose_name='véhicule'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.car', verbose_name='véhicule'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.car', verbose_name='véhicule'),
        ),
    ]
