# Generated by Django 3.2.4 on 2021-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='cost',
            field=models.FloatField(help_text='saisir le coût du carburant payée', verbose_name='coût'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='odometer_final_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Compteur final'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(help_text="Saisissez l'adresse de la société", max_length=100, verbose_name='adresse'),
        ),
    ]
